### ISSUE TITLE
Release beta version to be included into winit beta

### ISSUE THREAD

**Issue by kchibisov** [rust-mobile/android-activity#109]
cargo disallows publishing with unspecified dependencies, so every crate must be on crates.io when doing so.

**Comment by MarijnS95** [comment]
I will publish a beta for the ndk(-sys) crates and subsequently PR those here so that @rib can release an android-activity beta. I have a few more breaking changes to sort out and this should buy us some time.

**Comment by kchibisov** [comment]
I think `android-activity` doesn't depend on any new changes from ndk so we can release as is. @rib on `#winit` said the same if it matters, that he can just cut it, though, not sure when...

**Comment by MarijnS95** [comment]
@kchibisov that'd be very inconvenient to end-users if we intend to bump the `ndk` in `winit` but not in `android-activity`, leading to duplicate dependencies at best and unnecessary symbol/type incompatibilities at worst?

**Comment by kchibisov** [comment]
@MarijnS95 I need to bump `android-activity`, not `ndk` though.

**Comment by kchibisov** [comment]
Also, this is all for beta, because I can't publish winit beta because of android activity git dependency in winit right now. For the actual release we'll bump everything to stable versions.

**Comment by MarijnS95** [comment]
@kchibisov sure, all good if you/we still intend to do an `ndk` breaking bump in parallel with the `winit` release, just thought it may be useful to incorporate the `ndk` in the beta?

**Comment by kchibisov** [comment]
@MarijnS95 if you want to deal with it sure, but beta was nearly published until cargo complained about the `git` dependency, so it's sort of missed... it's not like we're in the rush, it's just a bit weird that I've merged the winit beta release PR and hasn't pushed it yet...

**Comment by rib** [comment]
Okey, I've just published `0.5.0-beta.0` to crates.io which winit should be able to use for its `beta.1` @kchibisov

**Comment by MarijnS95** [comment]
Just at the same time I thought to push for an NDK relese after all, guess I just missed out on the window... but as said above it doesn't really matter, though might be nice if we can include it in the next effort.

**Comment by rib** [comment]
I mean I could spin a beta.1 right now

**Comment by MarijnS95** [comment]
@rib thanks, let's use this opportunity then. Publishing as we speak, keep an eye out for the CI:

https://github.com/rust-mobile/ndk/actions/runs/5871521189

**Comment by MarijnS95** [comment]
It's done:

https://crates.io/crates/ndk-sys/versions
https://crates.io/crates/ndk/versions

And the upgrade on the `android-activity` side: https://github.com/rust-mobile/android-activity/pull/113

Thanks again!

**Comment by MarijnS95** [comment]
I bumped all these in `winit` as a test and it seems like everything is still compatible :tada:

**Comment by rib** [comment]
Okey, cool, `0.5.0-beta.1` published! :)

**Comment by rib** [comment]
thanks for the ndk/ndk-sys releases @MarijnS95!
