### ISSUE TITLE
Document cheap clonability of AndroidApp via Arc

### ISSUE THREAD

**Issue by A248** [rust-mobile/android-activity#125]
It is worth mentioning that AndroidApp can be cloned cheaply. If this behavior is documented, then callers can rely upon it as a contract. https://github.com/rust-mobile/android-activity/blob/219a14bda1745ff3a9983cf099d7822392cbb97c/android-activity/src/lib.rs#L451

**Comment by rib** [comment]
Right, it's intended to be something that can be relied on, so we should document that.
