### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by kchibisov** [rust-mobile/android-activity#129]
We are going to do a release of winit very soon, it's the last crate missing. The other android
crates were updated.

Requires https://github.com/rust-mobile/android-activity/pull/128

**Comment by rib** [comment]
Yeah I'll try and release soon.

For reference I'm expecting to need a small Winit PR for a breaking change in https://github.com/rust-mobile/android-activity/pull/131 that I'm hoping to land.
