### ISSUE TITLE
Expose Rust API for input method handling via the GameTextInput library

### ISSUE THREAD

**Issue by rib** [rust-mobile/android-activity#18]
For Android applications to be able to utilize soft keyboard UIs they need to be able to support the Android input methods protocol which the [GameTextInput](https://developer.android.com/games/agdk/game-activity/use-text-input) library helps with.

For reference this is the Winit IME API that was recently added that we should aim to be able to support: https://github.com/rust-windowing/winit/pull/2243 (and the original tracking issue: https://github.com/rust-windowing/winit/issues/1497)

Also see this Winit issue about supporting soft keyboards on Android: https://github.com/rust-windowing/winit/issues/2305

And here's an initial summary of what I found when considering supporting Winit's IME API on Android: https://github.com/rust-windowing/winit/issues/1497#issuecomment-1174053518

**Comment by Zoxc** [comment]
I've read up on things a bit now and it doesn't look like `GameTextInput` is compatible with Winit's IME model. It expects the application's text buffer state to be accessible to read and write while in Winit's IME model text flows from the IME into the application.

A temporary hack would be to drain `GameTextInput`'s state for characters and generate `ReceivedCharacter` from these to get some basic support.

**Comment by rib** [comment]
aah, okey, yeah interesting point.

Winit's IME abstraction is quite new, and was initially just aimed at supporting traditional desktop IME interfaces so it's not that surprising that it's not a good fit - though I hadn't realised that aspect about needing to be able to read back text entry state.

I would guess that we would be able to make additions to the Winit IME abstraction - so maybe it's something that we should first just get working in a branch - building on the android-activity-0.27 backend branch and hopefully it's possible to figure out a minimal addition that could support Android - and then whatever we add can probably just be stubbed out / ignored for platforms that don't need it.

I am a bit curious about this though - I would have thought other IMEs would also want to be able to sync with the contents of a text entry - unless they maybe only support appending text. I wonder if other platforms could maybe benefit from a way to access application text buffer state but they maybe didn't strictly need it.

**Comment by rib** [comment]
For example with Wayland there is a [set_surrounding_text](https://wayland.app/protocols/text-input-unstable-v3#zwp_text_input_v3:request:set_surrounding_text) protocol that can inform an IME about the existing contents of a text entry  and that also ties into a related [delete_surrounding_text](https://wayland.app/protocols/text-input-unstable-v3#zwp_text_input_v3:event:delete_surrounding_text) event that the IME can send for being able to delete characters from the original text.

**Comment by rib** [comment]
Also taking a look at the GTK API for IME handling they also have general support for sending surrounding text to an IME and also for an IME to be able to delete some of the surrounding text.

One initial proposal could just be to add a window API like `set_ime_surrounding_text()`.

**Comment by rib** [comment]
Just linking another Winit issue that looks related to this: https://github.com/rust-windowing/winit/issues/1823

**Comment by rib** [comment]
Just for reference here; there has been progress in `egui-winit` with adding IME support - so hopefully if the issues with https://github.com/rib/android-activity/pull/24 can be resolved (and the winit android-activity backend updated to use this API) then we will hopefully be able to test with the latest `egui-winit`

ref: https://github.com/emilk/egui/pull/2046
