### ISSUE TITLE
Any recommended way of integrating with Java/Kotlin code in an .aar library

### ISSUE THREAD

**Issue by rib** [rust-mobile/android-activity#55]
Hi, I'm trying to determine if it makes sense to try and use cargo-apk vs rolling something more hacky/specific while I'm not currently sure how to be able to integrate with Java code that's packaged as an .aar library.

In my case I'd like to be able to package, deploy and test code that will eventually be deployed as part of a Unity 3D application where I have a rust plugin and I'd like to use JNI to access bluetooth apis on Android.

Notably the Unity build system can conveniently let me drop in an .aar library with my compiled/packaged Java code so ideally I'd like to be able to build + deploy my own rust-based test harness in a similar way with the Java code provided as an aar library. (The turn around when building directly with Unity is terrible so I'm looking for a way to more rapidly build and test things in development)

If cargo-apk could perhaps also drive building the aar library, or something similar via gradlew that could also be convenient. I imagine it would be asking too much for cargo-apk to be handling the actual compilation of java code and way out of scope to handle pulling in java dependencies.

Are there perhaps some example projects that aren't purely native that give some ideas for how to best manage pulling together more complex packages that are a mixture of both native and non-native code?

Is there perhaps some way that I can tell cargo-apk to please include a given .aar library?

**Comment by iamralpht** [comment]
@Animeshz our Rust code exports a `JNI_OnLoad`, and that gets called via `System.loadLibrary` -- so it's just the same as a JNI shared object you'd write in C.

**Comment by rib** [comment]
So when I first opened this, I wasn't yet familiar with the scope of `cargo-apk` or `ndk-glue` etc and I think this was probably more a question of looking for an ideal toolchain that would make it easy to build apks based on a standalone native Rust application that was also utilizing Java/Kotlin code in an `.aar` library.

In the end I went with using a combo and `cargo ndk` and `Gradle`, since (at least at the time) I didn't find any mature tooling that could deal with both Rust and Java code (I tried mozilla's gradle plugin but hit bugs and also didn't want to use Gradle any more than strictly necessary)

I guess I originally opened this against `ndk-glue` and that's why @dvc94ch moved this to this repo, but maybe I should have originally opened it against `cargo apk`.

It's possible that `xbuild` can help with this now - I still need to get a chance to look at `xbuild` more closely.

Either way though I think it makes sense to close this issue now. It's not really an issue with `android-activity`

**Comment by MarijnS95** [comment]
> I guess I originally opened this against `ndk-glue` and that's why @dvc94ch moved this to this repo, but maybe I should have originally opened it against `cargo apk`.

Both were in the same repo back then, maybe it shouldn't have been transferred from `android-ndk-rs` to `android-activity` but `cargo-apk` instead?
