### ISSUE TITLE
Path target/aarch64-linux-android/debug/libapp.so doesn't exist

### ISSUE THREAD

**Issue by myname1111** [rust-mobile/android-activity#59]
I was trying to compile my program when suddenly I got this error

```
Error: Path `"E:\\Rust Projects\\flashcards_app\\target\\aarch64-linux-android\\debug\\libapp.so"` doesn't exist
```

Why does this happen?

**Comment by rib** [comment]
Sorry there isn't enough context here to guess what the problem could be, the description doesn't suggest that this is related to the `android-activity` crate either?

**Comment by myname1111** [comment]
It happened after I added Android activity and switched to cargo apk

I fixed it by removing the lib name

**Comment by rib** [comment]
ah right, yeah I don't think `cargo apk` currently supports custom library names unfortunately

**Comment by MarijnS95** [comment]
https://github.com/rust-mobile/cargo-subcommand/pull/17
