### ISSUE TITLE
Call `ANativeActivity_finish()` or `GameActivity_finish()` when `android_main` returns

### ISSUE THREAD

**Issue by rib** [rust-mobile/android-activity#67]
Additionally, expose an `AndroidApp::finish()` API that can be used to explicitly call the `Activity::finish()` method which will lead to the activity being stopped and destroyed (with a corresponding `Destroy` event)

**Comment by MarijnS95** [comment]
(Edited your message to include the full referenced doc-comment lines in-line :slightly_smiling_face:)

Indeed, we may have been wrong in assuming for and allowing the thread-spawn. Good to have the back-link to check our ideas, but at this point I'd say to go for it and call `finish()` after returning (and document this in the changelog), and see if anyone gets broken by it which seems unlikely given the above rules :)
